### ISSUE TITLE
Compatibility for iOS 14

### ISSUE THREAD

**Issue by ninjacarlo** [joemerlino/EnpassBypass#1]
Hi 
I’m on iPad with iPadOS 14.8
Could you update the code so that this tweak becomes compatible with 14.8 and with the latest Enpass 6.7.1

thanks so much for the support

**Comment by joemerlino** [comment]
Hi
I've just recompiled the tweak adding arm64e compatibility. Please download the deb package: https://github.com/joemerlino/EnpassBypass/blob/master/packages/com.joemerlino.enpassbypass_0.0.2_iphoneos-arm.deb and let me know if it works for you now.
Thank you

**Comment by ninjacarlo** [comment]
Yes it works!! Thank you so much ☺️☺️☺️
